= Google Cloud Spanner Hibernate Microprofile JPA Sample

This sample application demonstrates using https://microprofile.io/[Microprofile] with https://thorntail.io/[Thorntail] and JPA.

You should be able to use the same `persistence.xml` in any other JPA environments that's backed by Hibernate.

See https://github.com/GoogleCloudPlatform/google-cloud-spanner-hibernate/tree/master/google-cloud-spanner-hibernate-samples/spring-data-jpa-full-sample[this Cloud Spanner Spring Data JPA with Hibernate Sample]
for a sample application that shows all available Spanner features that can be used with Hibernate.

== Setup & Configuration
1. Create a Google Cloud Platform project.
2. https://cloud.google.com/docs/authentication/getting-started#creating_the_service_account[Create a service account] with Cloud Spanner permission.
Furnish a new JSON key and then set the credentials using the `GOOGLE_APPLICATION_CREDENTIALS` environment variable.
+
Alternatively, have the https://cloud.google.com/sdk/[Google Cloud SDK] installed and initialized and logged in with https://developers.google.com/identity/protocols/application-default-credentials[application default credentials].
+
----
gcloud auth application-default login
----
3. Enable the https://console.cloud.google.com/apis/api/spanner.googleapis.com/overview[Cloud Spanner API].

4. In the http://console.cloud.google.com/spanner[Spanner Cloud Console UI], create a Cloud Spanner instance and database and insert those details into the `javax.persistence.jdbc.url` defined in the file `src/main/resources/META-INF/persistence.xml`.
This setting configures the connection URL which specifies the database that your application will connect to.
+
 * Replace `${PROJECT_ID}` with your GCP project ID
 * Replace `${INSTANCE_ID}` with your Spanner instance ID
 * Replace `${DATABASE_NAME}` with the name of your Spanner database that you created inside your Spanner instance
----
<property name="javax.persistence.jdbc.url" value="jdbc:cloudspanner:/projects/${PROJECT_ID}/instances/${INSTANCE_ID}/databases/${DATABASE_NAME}" />
----

5. Open a terminal instance inside this directory and run `mvn package` to compile the application

6. Run the application: `java -jar target/microprofile-jpa-sample-thorntail.jar`

7. 6. Post a data entry with curl: `curl -XPOST -d'{"name": "Ray"}' -H"Content-Type: application/json"  http://localhost:8080/person`
+
You can view the data that was populated in your Cloud Spanner database by navigating to your database in the http://console.cloud.google.com/spanner[Spanner Console] view.
