version: 2
updates:       
 - package-ecosystem: maven
   directory: "/"
   schedule:
    interval: daily
   open-pull-requests-limit: 10
   commit-message:
    # Prefix all commit messages from dependabot with "deps:"
     prefix: "deps:"
     prefix-development: "test(deps):"
   ignore:
     - dependency-name: "io.quarkus:quarkus-universe-bom"
    # Quarkus 2 requires Java 11, which is too high.
       versions: ["2.x"]
