= Google Cloud Spanner Dialect for Hibernate ORM

This is a dialect compatible with https://hibernate.org/orm/releases/5.4/[Hibernate 5.4] for the https://cloud.google.com/spanner/[Google Cloud Spanner] database service.
The `SpannerDialect` produces SQL, DML, and DDL statements for most common entity types and relationships using standard Hibernate and Java Persistence annotations.

Please see the following sections for important details about dialect differences due to the unique features and limitations of Cloud Spanner.

== Quick Set-Up

First, add the Maven dependencies for the Cloud Spanner Hibernate Dialect and the Cloud Spanner JDBC driver.

Maven coordinates for the dialect:

[source,xml]
----
<dependency>
  <groupId>com.google.cloud</groupId>
  <artifactId>google-cloud-spanner-hibernate-dialect</artifactId>
  <version>1.2.0</version>
</dependency>
----

Maven coordinates for the official https://cloud.google.com/spanner/docs/open-source-jdbc[open source Cloud Spanner JDBC Driver].

[source,xml]
----
<dependency>
  <groupId>com.google.cloud</groupId>
  <artifactId>google-cloud-spanner-jdbc</artifactId>
  <version>1.15.0</version>
</dependency>
----

NOTE: Hibernate ORM with Cloud Spanner is officially supported only with the https://cloud.google.com/spanner/docs/open-source-jdbc[open source Cloud Spanner JDBC Driver].

If you're using a `SNAPSHOT` version of the dialect, please add the Sonatype Snapshots repository to your `pom.xml`:

[source,xml]
----
<repository>
  <id>snapshots-repo</id>
  <url>https://oss.sonatype.org/content/repositories/snapshots</url>
  <releases><enabled>false</enabled></releases>
  <snapshots><enabled>true</enabled></snapshots>
</repository>
----

Configuring the `SpannerDialect` and a Cloud Spanner Driver class is typical of all Hibernate dialects in the `hibernate.properties` file:

----
hibernate.dialect=com.google.cloud.spanner.hibernate.SpannerDialect
hibernate.connection.driver_class=com.google.cloud.spanner.jdbc.JdbcDriver
hibernate.connection.url=jdbc:cloudspanner:/projects/{INSERT_PROJECT_ID}/instances/{INSERT_INSTANCE_ID}/databases/{INSERT_DATABASE_ID}
----

The https://cloud.google.com/docs/authentication/getting-started[service account JSON credentials] file location should be in the `GOOGLE_APPLICATION_CREDENTIALS` environment variable.
The driver will use default credentials set in the Google Cloud SDK `gcloud` application otherwise.

You are now ready to begin using Hibernate with Cloud Spanner.

=== Multi-Database Support

In some cases, you will want to connect to multiple databases in the same project (for example connecting to Cloud Spanner for production and H2 for testing).

At the present moment, it is not possible to connect to another non-Spanner database through Hibernate if the Spanner dialect (`google-cloud-spanner-hibernate-dialect`) is on the project classpath.

In these cases, it is recommended to add the dialect dependency in a separate build profile to accommodate connecting to other databases. For example, in Maven, you might add a separate maven profile like this:

[source, xml]
----

<profiles>
  <profile>
    <id>spanner</id>
    <dependencies>
      <dependency>
        <groupId>com.google.cloud</groupId>
        <artifactId>google-cloud-spanner-hibernate-dialect</artifactId>
        <version>1.2.0</version>
      </dependency>
    </dependencies>
  </profile>
    ...
</profiles>
----

You can then activate the profile using `-Pspanner` such as `mvn compile -Pspanner`.

== User Guide

A user guide for the Cloud Spanner Hibernate Dialect is provided in the https://github.com/GoogleCloudPlatform/google-cloud-spanner-hibernate/wiki[repository wiki page].

This guide contains best practices for using the Hibernate dialect with Spanner which can improve the performance of your application.

== Cloud Spanner Hibernate ORM Limitations

The Cloud Spanner Hibernate Dialect supports most of the standard Hibernate and Java Persistence annotations, but there are minor differences in supported features because of differences in Cloud Spanner from other traditional SQL databases.

[options="header"]
|===
| Unsupported Feature | Description
| Large DML Transactions | Each Spanner transaction may only have up to 20,000 operations which modify rows of a table.
| Catalog and schema scoping for table names | Tables name references cannot contain periods or other punctuation.
| Column default values | The dialect does not set default values based on the `@ColumnDefault` annotation, because Cloud Spanner does not support column defaults in the DDL.
|===

=== Limit Large DML Transactions

Cloud Spanner has a mutation limit on each transaction - each Spanner transaction https://cloud.google.com/spanner/quotas#limits_for_creating_reading_updating_and_deleting_data[may only have up to 20,000 operations which modify rows of a table].

NOTE: Deleting a row counts as one operation and inserting/updating rows will count as a number of operations equal to the number of affected columns.
For example if one inserts a row that contains 5 columns, it counts as 5 modify operations for the insert.

Consequently, users must take care to avoid encountering these constraints.

1. We recommend being careful with the use of `CASCADE_TYPE.ALL` in Entity annotations because, depending on the application, it might trigger a large number of entities to be deleted in a single transaction and bring you over the 20,000 limit.
2. Also, when persisting a collection of entities, be mindful of the 20,000 mutations per transaction constraint.

=== Catalog/Schema Table Names

The Cloud Spanner Dialect only supports `@Table` with the `name` attribute.
It does not support table names with catalog and schema components because Spanner table names may not contain punctuation:

[source, java]
----
// Supported.
@Table(
  name = "book"
)

// Not supported: `public.store.book` is not a valid Cloud Spanner table name reference.
@Table(
  catalog = "public",
  schema = "store",
  name = "book"
)
----

=== Column Default Values

The dialect does not support the https://docs.jboss.org/hibernate/orm/5.4/javadocs/org/hibernate/annotations/ColumnDefault.html[`@ColumnDefault`] annotation
because Cloud Spanner does not offer a way of setting a default value for a column during table creation through DDL statements.

