= Cloud Spanner Hibernate Example

This sample application demonstrates using https://hibernate.org/orm/releases/5.4/[Hibernate 5.4] with https://cloud.google.com/spanner/[Google Cloud Spanner].


== Setup & Configuration
1. Create a Google Cloud Platform Project
2. https://cloud.google.com/docs/authentication/getting-started#creating_the_service_account[Create a service account] with Cloud Spanner permission.
Furnish a new JSON key and then set the credentials using the `GOOGLE_APPLICATION_CREDENTIALS` environment variable.
+
Alternatively, have the https://cloud.google.com/sdk/[Google Cloud SDK] installed and initialized and logged in with https://developers.google.com/identity/protocols/application-default-credentials[application default credentials].

3. Enable the https://console.cloud.google.com/apis/api/spanner.googleapis.com/overview[Cloud Spanner API]

4. Create a Cloud Spanner instance and database in your project and save those details for the next step.

== Run the Example
Run the example `main` method in `SampleApplication.java` while providing the connection details.

----
mvn exec:java -Dexec.mainClass="com.example.SampleApplication" -Dhibernate.connection.url="jdbc:cloudspanner:/projects/{YOUR_PROJECT_ID}/instances/{YOUR_INSTANCE_ID}/databases/{YOUR_DATABASE_ID}"
----

This example opens a transaction and saves a `Person` entity without specifying its `UUID`.
It also saves an associated `Payment` record for the person.

This insert query will appear in the application output:
----
Hibernate: insert into Payment (amount, id) values (?, ?)
Hibernate: insert into WireTransferPayment (wireId, id) values (?, ?)
Hibernate: insert into PersonsTable (address, name, nickname, payment_id, id) values (?, ?, ?, ?, ?)
----

The saved entities are then retrieved using an HQL query, and the stored person with the generated ID is printed:
----
Hibernate: select person0_.id as id1_0_, person0_.address as address2_0_, person0_.name as name3_0_, person0_.nickname as nickname4_0_ from PersonsTable person0_

There are 1 persons saved in the table:
Person{
 id=688377a3-b884-4beb-886d-6e93317c5542
 name='person'
 nickname='purson'
 address='address'
 payment_amount=200
}
----

You will also be able to view the tables and data that Hibernate created in Spanner through the https://console.cloud.google.com/spanner[Google Cloud Platform Console].
