/*
 * Copyright 2019-2020 Google LLC
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA
 */

package com.google.cloud.spanner.example.model;

import com.google.cloud.spanner.hibernate.BitReversedSequenceStyleGenerator;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToOne;
import java.util.UUID;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.id.enhanced.SequenceStyleGenerator;

/** Album - ID is generated by a bit-reversed sequence. */
@Entity
public class Album {

  /** Uses a table-backed sequence to generate values that are bit-reversed before being returned to the application. Bit-reversing the values makes them safe to use for a primary key in Cloud Spanner. It is recommended to use a separate sequence for each entity, and not share a single sequence for all the entities in your application. */
  @Id
  @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "albumId")
  @GenericGenerator(
      name = "albumId",
      strategy = "com.google.cloud.spanner.hibernate.BitReversedSequenceStyleGenerator",
      parameters = {
          @Parameter(name = SequenceStyleGenerator.SEQUENCE_PARAM, value = "albumId"),
          @Parameter(name = SequenceStyleGenerator.INCREMENT_PARAM, value = "1000"),
          @Parameter(name = SequenceStyleGenerator.INITIAL_PARAM, value = "1"),
          @Parameter(name = BitReversedSequenceStyleGenerator.EXCLUDE_RANGES_PARAM,
              value = "[-1000000,0]"),
      })
  @Column(nullable = false)
  private Long id;

  private String title;

  @ManyToOne private Singer singer;

  // Empty default constructor for Spring Data JPA.
  public Album() {}

  public Album(Singer singer, String title) {
    this.singer = singer;
    this.title = title;
  }

  public long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public String getTitle() {
    return title;
  }

  public void setTitle(String size) {
    this.title = size;
  }

  public Singer getSinger() {
    return singer;
  }

  public void setSinger(Singer customer) {
    this.singer = customer;
  }
}
