/*
 * Copyright 2019-2020 Google LLC
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA
 */

package com.google.cloud.spanner.example.model;

import com.google.cloud.spanner.hibernate.BitReversedSequenceStyleGenerator;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import java.util.ArrayList;
import java.util.List;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.id.enhanced.SequenceStyleGenerator;

/** Singer - ID is generated by a bit-reversed sequence. */
@Entity
public class Singer {

  /** Uses a table-backed sequence to generate values that are bit-reversed before being returned to the application. Bit-reversing the values makes them safe to use for a primary key in Cloud Spanner. It is recommended to use a separate sequence for each entity, and not share a single sequence for all the entities in your application. */
  @Id
  @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "singerId")
  @GenericGenerator(
             name = "singerId",
             strategy = "com.google.cloud.spanner.hibernate.BitReversedSequenceStyleGenerator",
             parameters = {
                 @Parameter(name = SequenceStyleGenerator.SEQUENCE_PARAM, value = "singerId"),
                 @Parameter(name = SequenceStyleGenerator.INCREMENT_PARAM, value = "1000"),
                 @Parameter(name = SequenceStyleGenerator.INITIAL_PARAM, value = "50000"),
                 @Parameter(name = BitReversedSequenceStyleGenerator.EXCLUDE_RANGES_PARAM,
                            value = "[1,1000] [10000,20000]"),
             })
  @Column(nullable = false)
  private Long id;

  private String name;

  @OneToMany(cascade = CascadeType.ALL, mappedBy = "singer")
  private List<Album> albums = new ArrayList<>();

  // Default constructor for Spring Data JPA.
  protected Singer() {}

  public Singer(String name) {
    this.name = name;
  }

  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public List<Album> getAlbums() {
    return albums;
  }

  public void setAlbums(List<Album> coffees) {
    this.albums = coffees;
  }
}
