steps:
  - name: maven:3-openjdk-11
    entrypoint: mvn
    args: ['install', '-DskipTests', '--batch-mode']

  - name: Run Samples Tests
    entrypoint: mvn
    args: [
        'verify',
        '-f',
        'google-cloud-spanner-hibernate-samples/pom.xml',
        '-Dhibernate.connection.url=$JDBC_URL',
        '-Dspring.datasource.url=$JDBC_URL',
        '-Dquarkus.datasource.jdbc.url=$JDBC_URL'
    ]
    env:
      - 'JDBC_URL=jdbc:cloudspanner:/projects/cloud-spanner-hibernate-ci/instances/test-instance/databases/hibernate-sample-db'

timeout: 3600s # 60 minutes

