# This workflow runs the integration tests in this project against a real Cloud Spanner instance.
name: Integration Tests on Cloud Spanner

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check-env:
    outputs:
      has-key: ${{ steps.project-id.outputs.defined }}
    runs-on: ubuntu-latest
    steps:
      - id: project-id
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        if: "${{ env.GCP_PROJECT_ID != '' }}"
        run: echo "defined=true" >> "$GITHUB_OUTPUT"
  build:
    needs: [check-env]
    if: needs.check-env.outputs.has-key == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - name: Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.JSON_SERVICE_ACCOUNT_CREDENTIALS }}

      - name: Install dependencies
        run: mvn install -DskipTests

      - name: Run Integration Tests
        working-directory: google-cloud-spanner-hibernate-dialect
        run: mvn -B verify
